kafka:
  bootstrapServers: "pkc-12576z.us-west2.gcp.confluent.cloud:9092"
  apiKey: "S55GEJ2ZEI3UPWCR"
  apiSecret: "6HMjpvY/o+i/+1s50polJAB2UDnksVj/Xk6gHlcl+C6iFYIV4HHq/PIQnmjME2I2"
  topic: "navi-dev-topic"
